import pandas as pd
from docling.document_converter import DocumentConverter

tea_gardens_bn = [
    "আল্লাদাদ",
    "আলিয়াবাগ",
    "আনয়শাবাগ",
    "বাহাদুরপুর",
    "ছোটনিখা",
    "ক্লীভ্ডন",
    "ধামাই",
    "দিদারপুর",
    "দিকুশা",
    "ফনিহবাগ",
    "হালফজ",
    "ইসলামাবাদ",
    "কালিকাবাড়ী",
    "কাপনাপাহাড়",
    "কুমারশাইল",
    "নিউসমনবাগ",
    "পাল্লাথল",
    "ফুলতলা",
    "রহমানিয়া",
    "রাজকী",
    "রশিদাবাদ",
    "রত্না",
    "শাহবাজপুর",
    "সাগরনাল",
    "শিলিয়ায়া",
    "সোনারুপা",
    "ওয়াহিদাবাদ",
    "দক্ষিণগুল",
    "লক্ষীছড়া",
    "শ্রীগোবিন্দপুর",
    "পাত্রখোলা",
    "দেউ",
    "শমসেরনগর",
    "চাম্পরাই",
    "কুরমা",
    "মাধবপুর",
    "মনোমোহনপুর",
    "নন্দরানী",
    "ফুলবাড়ী",
    "জঙ্গলবাড়ী",
    "মিরলিংগা",
    "চাতলাপুর",
    "আলীনগর",
    "আলমনাবাদ",
    "আজগরাবাদ",
    "বিজয়া",
    "চান্দবাগ",
    "ডালুছড়া",
    "ইটা",
    "করিমপুর",
    "গাজীপুর",
    "হাজীনগর",
    "হিঙ্গাজিয়া",
    "লিমাই",
    "কালিটি",
    "কাশিপুর",
    "লুয়ানী-হলিছড়া",
    "লংলা",
    "মেরিনা",
    "মনিপুর",
    "মোমিনছড়া",
    "উত্তরবাগ-ইন্দুনগর",
    "মুরাইছড়া",
    "পাল্লাকান্দি",
    "রাজনগর",
    "রেহেনা",
    "রাঙ্গিছড়া",
    "সিরাজনগর",
    "শফিনগর",
    "মাথিউড়া",
    "বোরহাননগর",
    "হাবিবনগর",
    "খান",
    "আফিফানগর",
    "লালখাল",
    "বুরজান",
    "খাদিম",
    "লোভাছড়া",
    "লাক্কাতুরা",
    "আলী বাহার",
    "জাফলং",
    "শ্রীপুর",
    "স্টার",
    "মালনীছড়া",
    "ডালিয়া",
    "ফনিহপুর",
    "দি মেলোয়া টি এস্টেট",
    "আমরাইল",
    "আমলী",
    "বালিশিরা",
    "ভাড়াউড়া",
    "বিলাসছড়া",
    "কেওয়ানাল",
    "দারাগাঁও",
    "ডিনস্টন",
    "দেওরাছড়া",
    "দিনারপুর",
    "হামিদিয়া",
    "হোসনাবাদ",
    "জুনেখানগর",
    "মৌলভী",
    "মাজদিহী",
    "মির্জাপুর",
    "এম আর খান",
    "নাহার",
    "নুরজাহান",
    "পারকুল",
    "প্রেমনগর",
    "রশিদপুর",
    "রাজঘাট",
    "সাইফ",
    "সাতগাঁও",
    "শ্রীবাড়ি",
    "জেরীন",
    "আমু",
    "চাকলাপুঞ্জি",
    "চান্দপুর",
    "লস্করপুর",
    "নালুয়া",
    "চলিছড়া",
    "জগদীশপুর",
    "তেলিয়াপাড়া",
    "দেউন্দি",
    "লালচান্দ",
    "নোয়াপাড়া",
    "বাওয়ানী",
    "বৈকুণ্ঠপুর",
    "বৃন্দাবন",
    "ইমাম",
    "মধুপুর",
    "সুরমা",
    "রেমা",
    "চাতলাছড়া",
]

tea_gardens_en = [
    "Alladad",
    "Aliyabag",
    "Anayeshabag",
    "Bahadurpur",
    "Chotonikha",
    "Clevedon",
    "Dhamai",
    "Didarpur",
    "Dikusha",
    "Fatehbagh",
    "Hafiz",
    "Islamabad",
    "Kalikabari",
    "Kapnapahar",
    "Kumarshail",
    "New Samanbag",
    "Pallathal",
    "Fultala",
    "Rahmania",
    "Rajki",
    "Rashidabad",
    "Ratna",
    "Shahbazpur",
    "Sagarnal",
    "Shiliyaya",
    "Sonarupa",
    "Wahidabad",
    "Dakshingul",
    "Lakkhichhara",
    "Sree Gobindapur",
    "Patrakhola",
    "Deundi",
    "Shamshernagar",
    "Champarai",
    "Kurma",
    "Madhabpur",
    "Monomohanpur",
    "Nandarani",
    "Fulbari",
    "Jangalbari",
    "Mirlinga",
    "Chatlapur",
    "Alinagar",
    "Alinabad",
    "Azgarabad",
    "Bijoya",
    "Chandbagh",
    "Daluchhara",
    "Ita",
    "Karimpur",
    "Gazipur",
    "Hajinagar",
    "Hingajia",
    "Limai",
    "Kaliti",
    "Kashipur",
    "Luyani-Halichhara",
    "Longla",
    "Merina",
    "Monipur",
    "Mominchhara",
    "Uttarbag-Indunagar",
    "Muraichhara",
    "Pallakandi",
    "Rajnagar",
    "Rehana",
    "Rangichhara",
    "Sirajnagar",
    "Shafinagar",
    "Mathiura",
    "Borhananagar",
    "Habibnagar",
    "Khan",
    "Afifnagar",
    "Lalkhal",
    "Burjan",
    "Khadim",
    "Lovachhara",
    "Lakkatura",
    "Ali Bahar",
    "Jaflong",
    "Sripur",
    "Star",
    "Malnichhara",
    "Dalia",
    "Fatehpur",
    "The Mellow Tea Estate",
    "Amrail",
    "Amli",
    "Balishira",
    "Bharauora",
    "Bilashchhara",
    "Kewachhara",
    "Daragaon",
    "Dinston",
    "Deorachhara",
    "Dinarpur",
    "Hamidia",
    "Hosnabad",
    "Junekhanagar",
    "Moulvi",
    "Majdihi",
    "Mirzapur",
    "M R Khan",
    "Nahar",
    "Nurjahan",
    "Parkul",
    "Premnagar",
    "Rashidpur",
    "Rajghat",
    "Saif",
    "Satgaon",
    "Sribari",
    "Jerin",
    "Amu",
    "Chaklapunji",
    "Chandpur",
    "Laskarpur",
    "Nalua",
    "Chalichhara",
    "Jagadishpur",
    "Teliapara",
    "Deundi",
    "Lalchand",
    "Noapara",
    "Bawani",
    "Baikunthapur",
    "Brindaban",
    "Imam",
    "Madhupur",
    "Surma",
    "Rema",
    "Chatlachhara",
]


def main(in_filename: str, out_filename: str, workers_file: str):
    converter = DocumentConverter()
    conv_res = converter.convert(in_filename)

    df_list: list[pd.DataFrame] = []

    for table in conv_res.document.tables:
        df_list.append(table.export_to_dataframe(conv_res.document))

    joined_df = pd.concat(df_list, ignore_index=True)
    joined_df = joined_df.iloc[:, [2, 3]].apply(pd.to_numeric)
    joined_df.columns = ["lat", "lon"]
    joined_df["tea_garden_bn"] = tea_gardens_bn
    joined_df["tea_garden_en"] = tea_gardens_en
    joined_df.loc[joined_df["tea_garden_en"] == "Chandpur", "lat"] = 24.14258
    joined_df.loc[joined_df["tea_garden_en"] == "Chandpur", "lon"] = 91.50746
    joined_df.loc[joined_df["tea_garden_en"] == "Bahadurpur", "lat"] = 24.707272
    joined_df.loc[joined_df["tea_garden_en"] == "Bahadurpur", "lon"] = 92.1917018
    joined_df.loc[joined_df["tea_garden_en"] == "Bawani", "lat"] = 24.4427315
    joined_df.loc[joined_df["tea_garden_en"] == "Bawani", "lon"] = 91.5749329
    joined_df.loc[joined_df["tea_garden_en"] == "Afifnagar", "lat"] = 25.1209121
    joined_df.loc[joined_df["tea_garden_en"] == "Afifnagar", "lon"] = 92.1884599

    worker_df = pd.read_csv(workers_file)
    joined_df = joined_df.join(worker_df, validate="one_to_one")

    joined_df.to_csv(out_filename, index=False)


if __name__ == "__main__":
    in_filename = "data/raw/tea.pdf"
    out_filename = "data/intermediate/tea_lat_lon.csv"
    workers_file = "data/raw/tea_workers.csv"
    main(in_filename, out_filename, workers_file)
